use std::collections::HashMap;
use std::fmt::Write;

use crate::codegen::{
    CodegenError, check_errors, check_no_dirty_instances, collect_internal_nets,
    collect_top_intermediates, find_top_port_context, port_type_to_sv, port_type_to_sv_wire,
    resolve_port_type,
};
use crate::nets::{Nets, resolve_nets};
use crate::schematic::Diagnostic;
use crate::types::*;

/// Generate structural SystemVerilog from a schematic.
pub fn generate_sv(
    schematic: &Schematic,
    library: &[ModuleDef],
    diagnostics: &[Diagnostic],
) -> Result<String, CodegenError> {
    check_errors(diagnostics)?;
    check_no_dirty_instances(schematic)?;

    let lib_map: HashMap<&str, &ModuleDef> = library.iter().map(|m| (m.name.as_str(), m)).collect();

    let mut out = String::new();

    // Header comment
    writeln!(
        out,
        "// Generated by hdl-compose. Edit the source .hdlc project file, not this file."
    )
    .unwrap();
    writeln!(out).unwrap();

    // Module declaration
    emit_module_header(&mut out, schematic, library);

    writeln!(out).unwrap();

    // Resolve connectivity once; declarations and port-map rendering all
    // derive from the same net view.
    let nets = resolve_nets(schematic, library);

    // Top-port intermediate wires + assigns. Every connected non-inout top
    // port routes through an intermediate so internal references all use a
    // single canonical name.
    let top_intermediates = collect_top_intermediates(schematic, &nets);
    for ti in &top_intermediates {
        let type_str = port_type_to_sv_wire(&ti.port_type);
        writeln!(out, "  {type_str} {};", ti.sig_name).unwrap();
    }
    if !top_intermediates.is_empty() {
        writeln!(out).unwrap();
        for ti in &top_intermediates {
            match ti.direction {
                Direction::In => {
                    writeln!(out, "  assign {} = {};", ti.sig_name, ti.port_name).unwrap();
                }
                Direction::Out => {
                    writeln!(out, "  assign {} = {};", ti.port_name, ti.sig_name).unwrap();
                }
                Direction::InOut => {}
            }
        }
        writeln!(out).unwrap();
    }

    // Wire declarations for internal nets
    let internal_nets = collect_internal_nets(&nets);
    for (sig_name, port_type) in &internal_nets {
        let type_str = port_type_to_sv_wire(port_type);
        writeln!(out, "  {type_str} {sig_name};").unwrap();
    }
    if !internal_nets.is_empty() {
        writeln!(out).unwrap();
    }

    // Instance statements (alphabetical)
    let mut sorted_instances: Vec<&Instance> = schematic.instances.iter().collect();
    sorted_instances.sort_by(|a, b| a.name.cmp(&b.name));

    for inst in &sorted_instances {
        if let Some(module) = lib_map.get(inst.module_ref.as_str()) {
            emit_instance(&mut out, &nets, inst, module);
            writeln!(out).unwrap();
        }
    }

    writeln!(out, "endmodule").unwrap();

    Ok(out)
}

fn emit_module_header(out: &mut String, schematic: &Schematic, library: &[ModuleDef]) {
    write!(out, "module {}", schematic.top_name).unwrap();

    // Parameters
    if !schematic.top_generics.is_empty() {
        writeln!(out, " #(").unwrap();
        for (i, g) in schematic.top_generics.iter().enumerate() {
            let sep = if i < schematic.top_generics.len() - 1 {
                ","
            } else {
                ""
            };
            if let Some(default) = &g.default_value {
                writeln!(
                    out,
                    "  parameter {} {} = {}{}",
                    g.type_name, g.name, default, sep
                )
                .unwrap();
            } else {
                writeln!(out, "  parameter {} {}{}", g.type_name, g.name, sep).unwrap();
            }
        }
        write!(out, ")").unwrap();
    }

    // Ports
    if !schematic.top_ports.is_empty() {
        writeln!(out, " (").unwrap();
        for (i, p) in schematic.top_ports.iter().enumerate() {
            let sep = if i < schematic.top_ports.len() - 1 {
                ","
            } else {
                ""
            };
            let dir = match p.direction {
                Direction::In => "input",
                Direction::Out => "output",
                Direction::InOut => "inout",
            };
            let resolved_type = match find_top_port_context(schematic, library, &p.name) {
                Some((mg, gm)) => resolve_port_type(&p.port_type, mg, gm),
                None => p.port_type.clone(),
            };
            let type_str = port_type_to_sv(&resolved_type);
            writeln!(out, "  {} {} {}{}", dir, type_str, p.name, sep).unwrap();
        }
        writeln!(out, ");").unwrap();
    } else {
        writeln!(out, "();").unwrap();
    }
}

fn emit_instance(out: &mut String, nets: &Nets, inst: &Instance, module: &ModuleDef) {
    write!(out, "  {}", inst.module_ref).unwrap();

    // Parameter overrides
    if !inst.generic_map.is_empty() {
        writeln!(out, " #(").unwrap();
        let mut generics: Vec<_> = inst.generic_map.iter().collect();
        generics.sort_by_key(|(k, _)| {
            module
                .generics
                .iter()
                .position(|g| g.name == **k)
                .unwrap_or(usize::MAX)
        });

        for (i, (name, value)) in generics.iter().enumerate() {
            let sep = if i < generics.len() - 1 { "," } else { "" };
            writeln!(out, "    .{name}({value}){sep}").unwrap();
        }
        write!(out, "  )").unwrap();
    }

    writeln!(out, " {} (", inst.name).unwrap();

    // Port connections (module declaration order)
    for (i, port) in module.ports.iter().enumerate() {
        let sep = if i < module.ports.len() - 1 { "," } else { "" };
        // A port with no entry of its own can still be on a net (another pin
        // references it) — connect it rather than leaving the net undriven.
        let pin = NetRef::InstancePort(inst.name.clone(), port.name.clone());
        let rhs = match inst.port_map.get(&port.name) {
            Some(Some(net_ref)) => render_rhs_sv(nets, net_ref),
            Some(None) | None => match nets.name_for(&pin) {
                Some(name) => name.to_string(),
                None => String::new(), // empty parens for unconnected
            },
        };
        let lhs = match inst.consumer_slices.get(&port.name) {
            Some(SliceExpr::Bit(b)) => format!("{}[{}]", port.name, b),
            Some(SliceExpr::Range { high, low }) => format!("{}[{}:{}]", port.name, high, low),
            None => port.name.clone(),
        };
        writeln!(out, "    .{}({}){}", lhs, rhs, sep).unwrap();
    }
    writeln!(out, "  );").unwrap();
}

/// Render a NetRef as a SystemVerilog expression. Slice variants use
/// `[i]` for a single bit and `[high:low]` for a range.
fn render_rhs_sv(nets: &Nets, net_ref: &NetRef) -> String {
    let base_name = nets
        .name_for(net_ref)
        .expect("rendered ref is always a net member")
        .to_string();
    match net_ref {
        NetRef::TopPort(_) | NetRef::InstancePort(_, _) => base_name,
        NetRef::TopPortSlice(_, slice) | NetRef::InstancePortSlice(_, _, slice) => {
            match slice {
                SliceExpr::Bit(i) => format!("{base_name}[{i}]"),
                SliceExpr::Range { high, low } => format!("{base_name}[{high}:{low}]"),
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::Schematic;

    fn simple_schematic() -> (Schematic, Vec<ModuleDef>) {
        let mut s = Schematic::new("top_level", Language::SystemVerilog);
        s.top_ports.push(PortDef {
            name: "clk".into(),
            direction: Direction::In,
            port_type: PortType::StdLogic,
            bundle: None,
        });
        s.top_ports.push(PortDef {
            name: "led".into(),
            direction: Direction::Out,
            port_type: PortType::StdLogicVector(Range {
                high: RangeExpr::Literal(7),
                low: RangeExpr::Literal(0),
                dir: RangeDir::Downto,
            }),
            bundle: None,
        });

        s.add_instance("u_counter", "counter").unwrap();
        s.set_port_map_entry("u_counter", "clk", Some(NetRef::TopPort("clk".into())))
            .unwrap();
        s.set_port_map_entry("u_counter", "count", Some(NetRef::TopPort("led".into())))
            .unwrap();

        let lib = vec![ModuleDef {
            name: "counter".into(),
            generics: vec![],
            ports: vec![
                PortDef {
                    name: "clk".into(),
                    direction: Direction::In,
                    port_type: PortType::StdLogic,
                    bundle: None,
                },
                PortDef {
                    name: "count".into(),
                    direction: Direction::Out,
                    port_type: PortType::StdLogicVector(Range {
                        high: RangeExpr::Literal(7),
                        low: RangeExpr::Literal(0),
                        dir: RangeDir::Downto,
                    }),
                    bundle: None,
                },
            ],
            source_path: "counter.sv".into(),
            source_hash: 0,
            dependencies: Vec::new(),
        }];

        (s, lib)
    }

    #[test]
    fn generates_valid_sv() {
        let (s, lib) = simple_schematic();
        let diags = s.validate(&lib);
        let output = generate_sv(&s, &lib, &diags).unwrap();

        assert!(output.contains("// Generated by hdl-compose"));
        assert!(output.contains("module top_level"));
        assert!(output.contains("input logic clk"));
        assert!(output.contains("output logic [7:0] led"));
        assert!(output.contains("counter u_counter"));
        // Top ports route through intermediates: `clk_s` and `led_s`.
        assert!(output.contains("assign clk_s = clk;"));
        assert!(output.contains("assign led = led_s;"));
        assert!(output.contains(".clk(clk_s)"));
        assert!(output.contains(".count(led_s)"));
        assert!(output.contains("endmodule"));
    }

    #[test]
    fn internal_wire_declaration() {
        let mut s = Schematic::new("top", Language::SystemVerilog);
        s.add_instance("u_a", "mod_a").unwrap();
        s.add_instance("u_b", "mod_b").unwrap();
        s.set_port_map_entry(
            "u_b",
            "din",
            Some(NetRef::InstancePort("u_a".into(), "dout".into())),
        )
        .unwrap();

        let lib = vec![
            ModuleDef {
                name: "mod_a".into(),
                generics: vec![],
                ports: vec![PortDef {
                    name: "dout".into(),
                    direction: Direction::Out,
                    port_type: PortType::StdLogic,
                    bundle: None,
                }],
                source_path: "a.sv".into(),
                source_hash: 0,
                dependencies: Vec::new(),
            },
            ModuleDef {
                name: "mod_b".into(),
                generics: vec![],
                ports: vec![PortDef {
                    name: "din".into(),
                    direction: Direction::In,
                    port_type: PortType::StdLogic,
                    bundle: None,
                }],
                source_path: "b.sv".into(),
                source_hash: 0,
                dependencies: Vec::new(),
            },
        ];

        let diags = s.validate(&lib);
        let output = generate_sv(&s, &lib, &diags).unwrap();

        assert!(output.contains("wire u_a_dout;"));
        assert!(output.contains(".din(u_a_dout)"));
    }

    #[test]
    fn empty_parens_for_unconnected() {
        let mut s = Schematic::new("top", Language::SystemVerilog);
        s.add_instance("u_a", "mod_a").unwrap();

        let lib = vec![ModuleDef {
            name: "mod_a".into(),
            generics: vec![],
            ports: vec![PortDef {
                name: "unused".into(),
                direction: Direction::Out,
                port_type: PortType::StdLogic,
                bundle: None,
            }],
            source_path: "a.sv".into(),
            source_hash: 0,
            dependencies: Vec::new(),
        }];

        let diags: Vec<crate::schematic::Diagnostic> = s
            .validate(&lib)
            .into_iter()
            .filter(|d| d.is_error())
            .collect();

        let output = generate_sv(&s, &lib, &diags).unwrap();
        assert!(output.contains(".unused()"));
    }

    #[test]
    fn refuses_on_error() {
        let mut s = Schematic::new("top", Language::SystemVerilog);
        s.add_instance("u_fifo", "nonexistent").unwrap();

        let diags = s.validate(&[]);
        let result = generate_sv(&s, &[], &diags);
        assert!(result.is_err());
    }

    #[test]
    fn no_component_declarations() {
        let (s, lib) = simple_schematic();
        let diags = s.validate(&lib);
        let output = generate_sv(&s, &lib, &diags).unwrap();

        assert!(!output.contains("component"));
    }

    #[test]
    fn slice_variants_render_sv() {
        let mut s = Schematic::new("top", Language::SystemVerilog);
        s.add_instance("u_a", "mod_a").unwrap();
        s.add_instance("u_b", "mod_b").unwrap();
        s.set_port_map_entry(
            "u_b",
            "din1",
            Some(NetRef::InstancePortSlice(
                "u_a".into(),
                "bus".into(),
                SliceExpr::Bit(0),
            )),
        )
        .unwrap();
        s.set_port_map_entry(
            "u_b",
            "din2",
            Some(NetRef::InstancePortSlice(
                "u_a".into(),
                "bus".into(),
                SliceExpr::Range { high: 7, low: 4 },
            )),
        )
        .unwrap();

        let bus_type = PortType::StdLogicVector(Range {
            high: RangeExpr::Literal(7),
            low: RangeExpr::Literal(0),
            dir: RangeDir::Downto,
        });
        let din1_type = PortType::StdLogic;
        let din2_type = PortType::StdLogicVector(Range {
            high: RangeExpr::Literal(3),
            low: RangeExpr::Literal(0),
            dir: RangeDir::Downto,
        });
        let lib = vec![
            ModuleDef {
                name: "mod_a".into(),
                generics: vec![],
                ports: vec![PortDef {
                    name: "bus".into(),
                    direction: Direction::Out,
                    port_type: bus_type,
                    bundle: None,
                }],
                source_path: "a.sv".into(),
                source_hash: 0,
                dependencies: Vec::new(),
            },
            ModuleDef {
                name: "mod_b".into(),
                generics: vec![],
                ports: vec![
                    PortDef {
                        name: "din1".into(),
                        direction: Direction::In,
                        port_type: din1_type,
                        bundle: None,
                    },
                    PortDef {
                        name: "din2".into(),
                        direction: Direction::In,
                        port_type: din2_type,
                        bundle: None,
                    },
                ],
                source_path: "b.sv".into(),
                source_hash: 0,
                dependencies: Vec::new(),
            },
        ];

        let diags: Vec<crate::schematic::Diagnostic> = s
            .validate(&lib)
            .into_iter()
            .filter(|d| d.is_error())
            .collect();
        let output = generate_sv(&s, &lib, &diags).unwrap();
        assert!(output.contains(".din1(u_a_bus[0])"), "{output}");
        assert!(output.contains(".din2(u_a_bus[7:4])"), "{output}");
    }

    #[test]
    fn bilateral_slice_codegen_sv() {
        let mut s = Schematic::new("top", Language::SystemVerilog);
        s.add_instance("u_a", "mod_a").unwrap();
        s.add_instance("u_b", "mod_b").unwrap();
        s.set_port_map_entry(
            "u_b",
            "din",
            Some(NetRef::InstancePortSlice(
                "u_a".into(),
                "dout".into(),
                SliceExpr::Range { high: 7, low: 4 },
            )),
        )
        .unwrap();
        s.instances
            .iter_mut()
            .find(|i| i.name == "u_b")
            .unwrap()
            .consumer_slices
            .insert("din".into(), SliceExpr::Range { high: 3, low: 0 });

        let lib = vec![
            ModuleDef {
                name: "mod_a".into(),
                generics: vec![],
                ports: vec![PortDef {
                    name: "dout".into(),
                    direction: Direction::Out,
                    port_type: PortType::StdLogicVector(Range {
                        high: RangeExpr::Literal(7),
                        low: RangeExpr::Literal(0),
                        dir: RangeDir::Downto,
                    }),
                    bundle: None,
                }],
                source_path: "a.sv".into(),
                source_hash: 0,
                dependencies: Vec::new(),
            },
            ModuleDef {
                name: "mod_b".into(),
                generics: vec![],
                ports: vec![PortDef {
                    name: "din".into(),
                    direction: Direction::In,
                    port_type: PortType::StdLogicVector(Range {
                        high: RangeExpr::Literal(7),
                        low: RangeExpr::Literal(0),
                        dir: RangeDir::Downto,
                    }),
                    bundle: None,
                }],
                source_path: "b.sv".into(),
                source_hash: 0,
                dependencies: Vec::new(),
            },
        ];

        let diags: Vec<crate::schematic::Diagnostic> = s
            .validate(&lib)
            .into_iter()
            .filter(|d| d.is_error())
            .collect();
        let output = generate_sv(&s, &lib, &diags).unwrap();
        assert!(
            output.contains(".din[3:0](u_a_dout[7:4])"),
            "missing bilateral slice in SV output:\n{output}"
        );
    }
}
