use std::collections::HashMap;
use std::fmt::Write;

use crate::codegen::{
    CodegenError, check_errors, check_no_dirty_instances, collect_internal_nets,
    collect_top_intermediates, find_top_port_context, port_type_to_vhdl,
    port_type_to_vhdl_signal, resolve_port_type,
};
use crate::schematic::Diagnostic;
use crate::types::*;

/// Generate structural VHDL from a schematic.
pub fn generate_vhdl(
    schematic: &Schematic,
    library: &[ModuleDef],
    diagnostics: &[Diagnostic],
) -> Result<String, CodegenError> {
    check_errors(diagnostics)?;
    check_no_dirty_instances(schematic)?;

    let lib_map: HashMap<&str, &ModuleDef> = library.iter().map(|m| (m.name.as_str(), m)).collect();

    let mut out = String::new();

    // Header comment
    writeln!(
        out,
        "-- Generated by hdl-compose. Edit the source .hdlc project file, not this file."
    )
    .unwrap();
    writeln!(out).unwrap();

    // Library/use
    writeln!(out, "library ieee;").unwrap();
    writeln!(out, "use ieee.std_logic_1164.all;").unwrap();
    writeln!(out).unwrap();

    // Entity declaration
    emit_entity(&mut out, schematic, library);

    writeln!(out).unwrap();

    // Architecture
    writeln!(out, "architecture structural of {} is", schematic.top_name).unwrap();
    writeln!(out).unwrap();

    // Signal declarations: top-port intermediates first (every connected
    // non-inout top port gets its own signal, so internal references all use
    // the intermediate name and no port_map maps directly to the entity port).
    let top_intermediates = collect_top_intermediates(schematic, library);
    for ti in &top_intermediates {
        let type_str = port_type_to_vhdl_signal(&ti.port_type);
        writeln!(out, "  signal {} : {};", ti.sig_name, type_str).unwrap();
    }
    if !top_intermediates.is_empty() {
        writeln!(out).unwrap();
    }

    // Internal nets (instance-driven nets shared across the design).
    let internal_nets = collect_internal_nets(schematic, library);
    for (_, sig_name, port_type) in &internal_nets {
        let type_str = port_type_to_vhdl_signal(port_type);
        writeln!(out, "  signal {sig_name} : {type_str};").unwrap();
    }
    if !internal_nets.is_empty() {
        writeln!(out).unwrap();
    }

    // Component declarations
    let mut seen_modules = Vec::new();
    let mut sorted_instances: Vec<&Instance> = schematic.instances.iter().collect();
    sorted_instances.sort_by(|a, b| a.name.cmp(&b.name));

    for inst in &sorted_instances {
        if !seen_modules.contains(&inst.module_ref) {
            if let Some(module) = lib_map.get(inst.module_ref.as_str()) {
                emit_component(&mut out, module);
                writeln!(out).unwrap();
            }
            seen_modules.push(inst.module_ref.clone());
        }
    }

    writeln!(out, "begin").unwrap();
    writeln!(out).unwrap();

    // Top-port pass-through assignments. Inputs feed the intermediate from the
    // entity port; outputs feed the entity port from the intermediate.
    for ti in &top_intermediates {
        match ti.direction {
            Direction::In => {
                writeln!(out, "  {} <= {};", ti.sig_name, ti.port_name).unwrap();
            }
            Direction::Out => {
                writeln!(out, "  {} <= {};", ti.port_name, ti.sig_name).unwrap();
            }
            Direction::InOut => {}
        }
    }
    if !top_intermediates.is_empty() {
        writeln!(out).unwrap();
    }

    // Instance statements (alphabetical)
    for inst in &sorted_instances {
        if let Some(module) = lib_map.get(inst.module_ref.as_str()) {
            emit_instance(&mut out, schematic, inst, module);
            writeln!(out).unwrap();
        }
    }

    writeln!(out, "end architecture structural;").unwrap();

    Ok(out)
}

fn emit_entity(out: &mut String, schematic: &Schematic, library: &[ModuleDef]) {
    writeln!(out, "entity {} is", schematic.top_name).unwrap();

    // Generics
    if !schematic.top_generics.is_empty() {
        writeln!(out, "  generic (").unwrap();
        for (i, g) in schematic.top_generics.iter().enumerate() {
            let sep = if i < schematic.top_generics.len() - 1 {
                ";"
            } else {
                ""
            };
            if let Some(default) = &g.default_value {
                writeln!(
                    out,
                    "    {} : {} := {}{}",
                    g.name, g.type_name, default, sep
                )
                .unwrap();
            } else {
                writeln!(out, "    {} : {}{}", g.name, g.type_name, sep).unwrap();
            }
        }
        writeln!(out, "  );").unwrap();
    }

    // Ports
    if !schematic.top_ports.is_empty() {
        writeln!(out, "  port (").unwrap();
        for (i, p) in schematic.top_ports.iter().enumerate() {
            let sep = if i < schematic.top_ports.len() - 1 {
                ";"
            } else {
                ""
            };
            let dir = match p.direction {
                Direction::In => "in",
                Direction::Out => "out",
                Direction::InOut => "inout",
            };
            let resolved_type = match find_top_port_context(schematic, library, &p.name) {
                Some((mg, gm)) => resolve_port_type(&p.port_type, mg, gm),
                None => p.port_type.clone(),
            };
            let type_str = port_type_to_vhdl(&resolved_type);
            writeln!(out, "    {} : {} {}{}", p.name, dir, type_str, sep).unwrap();
        }
        writeln!(out, "  );").unwrap();
    }

    writeln!(out, "end entity {};", schematic.top_name).unwrap();
}

fn emit_component(out: &mut String, module: &ModuleDef) {
    writeln!(out, "  component {} is", module.name).unwrap();

    if !module.generics.is_empty() {
        writeln!(out, "    generic (").unwrap();
        for (i, g) in module.generics.iter().enumerate() {
            let sep = if i < module.generics.len() - 1 {
                ";"
            } else {
                ""
            };
            if let Some(default) = &g.default_value {
                writeln!(
                    out,
                    "      {} : {} := {}{}",
                    g.name, g.type_name, default, sep
                )
                .unwrap();
            } else {
                writeln!(out, "      {} : {}{}", g.name, g.type_name, sep).unwrap();
            }
        }
        writeln!(out, "    );").unwrap();
    }

    if !module.ports.is_empty() {
        writeln!(out, "    port (").unwrap();
        for (i, p) in module.ports.iter().enumerate() {
            let sep = if i < module.ports.len() - 1 { ";" } else { "" };
            let dir = match p.direction {
                Direction::In => "in",
                Direction::Out => "out",
                Direction::InOut => "inout",
            };
            let type_str = port_type_to_vhdl(&p.port_type);
            writeln!(out, "      {} : {} {}{}", p.name, dir, type_str, sep).unwrap();
        }
        writeln!(out, "    );").unwrap();
    }

    writeln!(out, "  end component {};", module.name).unwrap();
}

fn emit_instance(out: &mut String, schematic: &Schematic, inst: &Instance, module: &ModuleDef) {
    write!(out, "  {} : {}", inst.name, inst.module_ref).unwrap();

    // Generic map
    if !inst.generic_map.is_empty() {
        writeln!(out).unwrap();
        writeln!(out, "    generic map (").unwrap();
        let mut generics: Vec<_> = inst.generic_map.iter().collect();
        generics.sort_by_key(|(k, _)| {
            module
                .generics
                .iter()
                .position(|g| g.name == **k)
                .unwrap_or(usize::MAX)
        });

        for (i, (name, value)) in generics.iter().enumerate() {
            let sep = if i < generics.len() - 1 { "," } else { "" };
            writeln!(out, "      {} => {}{}", name, value, sep).unwrap();
        }
        writeln!(out, "    )").unwrap();
    } else {
        writeln!(out).unwrap();
    }

    // Port map
    writeln!(out, "    port map (").unwrap();
    // Emit ports in module declaration order
    for (i, port) in module.ports.iter().enumerate() {
        let sep = if i < module.ports.len() - 1 { "," } else { "" };
        let rhs = match inst.port_map.get(&port.name) {
            Some(Some(net_ref)) => render_rhs_vhdl(schematic, net_ref),
            Some(None) | None => "open".to_string(),
        };
        let lhs = match inst.consumer_slices.get(&port.name) {
            Some(SliceExpr::Bit(b)) => format!("{}({})", port.name, b),
            Some(SliceExpr::Range { high, low }) => {
                format!("{}({} downto {})", port.name, high, low)
            }
            None => port.name.clone(),
        };
        writeln!(out, "      {} => {}{}", lhs, rhs, sep).unwrap();
    }
    writeln!(out, "    );").unwrap();
}

/// Render a NetRef as a VHDL association RHS. Slice variants use
/// `(i)` for a single bit and `(high downto low)` for a range.
fn render_rhs_vhdl(schematic: &Schematic, net_ref: &NetRef) -> String {
    let base_name = schematic.signal_name(net_ref);
    match net_ref {
        NetRef::TopPort(_) | NetRef::InstancePort(_, _) => base_name,
        NetRef::TopPortSlice(_, slice) | NetRef::InstancePortSlice(_, _, slice) => {
            match slice {
                SliceExpr::Bit(i) => format!("{base_name}({i})"),
                SliceExpr::Range { high, low } => {
                    format!("{base_name}({high} downto {low})")
                }
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::Schematic;

    fn simple_schematic() -> (Schematic, Vec<ModuleDef>) {
        let mut s = Schematic::new("top_level", Language::Vhdl);
        s.top_ports.push(PortDef {
            name: "clk".into(),
            direction: Direction::In,
            port_type: PortType::StdLogic,
            bundle: None,
        });
        s.top_ports.push(PortDef {
            name: "led".into(),
            direction: Direction::Out,
            port_type: PortType::StdLogicVector(Range {
                high: RangeExpr::Literal(7),
                low: RangeExpr::Literal(0),
                dir: RangeDir::Downto,
            }),
            bundle: None,
        });

        s.add_instance("u_counter", "counter").unwrap();
        s.set_port_map_entry("u_counter", "clk", Some(NetRef::TopPort("clk".into())))
            .unwrap();
        s.set_port_map_entry("u_counter", "count", Some(NetRef::TopPort("led".into())))
            .unwrap();

        let lib = vec![ModuleDef {
            name: "counter".into(),
            generics: vec![],
            ports: vec![
                PortDef {
                    name: "clk".into(),
                    direction: Direction::In,
                    port_type: PortType::StdLogic,
                    bundle: None,
                },
                PortDef {
                    name: "count".into(),
                    direction: Direction::Out,
                    port_type: PortType::StdLogicVector(Range {
                        high: RangeExpr::Literal(7),
                        low: RangeExpr::Literal(0),
                        dir: RangeDir::Downto,
                    }),
                    bundle: None,
                },
            ],
            source_path: "counter.vhd".into(),
            source_hash: 0,
            dependencies: Vec::new(),
        }];

        (s, lib)
    }

    #[test]
    fn generates_valid_vhdl() {
        let (s, lib) = simple_schematic();
        let diags = s.validate(&lib);
        let output = generate_vhdl(&s, &lib, &diags).unwrap();

        assert!(output.contains("-- Generated by hdl-compose"));
        assert!(output.contains("library ieee;"));
        assert!(output.contains("entity top_level is"));
        assert!(output.contains("architecture structural of top_level is"));
        assert!(output.contains("component counter is"));
        assert!(output.contains("u_counter : counter"));
        // Top ports route through intermediates.
        assert!(output.contains("signal clk_s : std_logic;"));
        assert!(output.contains("signal led_s : std_logic_vector(7 downto 0);"));
        assert!(output.contains("clk_s <= clk;"));
        assert!(output.contains("led <= led_s;"));
        assert!(output.contains("clk => clk_s"));
        assert!(output.contains("count => led_s"));
        assert!(output.contains("end architecture structural;"));
    }

    #[test]
    fn internal_net_signal_declaration() {
        let mut s = Schematic::new("top", Language::Vhdl);
        s.add_instance("u_a", "mod_a").unwrap();
        s.add_instance("u_b", "mod_b").unwrap();
        s.set_port_map_entry(
            "u_b",
            "din",
            Some(NetRef::InstancePort("u_a".into(), "dout".into())),
        )
        .unwrap();

        let lib = vec![
            ModuleDef {
                name: "mod_a".into(),
                generics: vec![],
                ports: vec![PortDef {
                    name: "dout".into(),
                    direction: Direction::Out,
                    port_type: PortType::StdLogic,
                    bundle: None,
                }],
                source_path: "a.vhd".into(),
                source_hash: 0,
                dependencies: Vec::new(),
            },
            ModuleDef {
                name: "mod_b".into(),
                generics: vec![],
                ports: vec![PortDef {
                    name: "din".into(),
                    direction: Direction::In,
                    port_type: PortType::StdLogic,
                    bundle: None,
                }],
                source_path: "b.vhd".into(),
                source_hash: 0,
                dependencies: Vec::new(),
            },
        ];

        let diags = s.validate(&lib);
        let output = generate_vhdl(&s, &lib, &diags).unwrap();

        assert!(output.contains("signal u_a_dout : std_logic;"));
        assert!(output.contains("din => u_a_dout"));
    }

    #[test]
    fn aliased_signal_name() {
        let mut s = Schematic::new("top", Language::Vhdl);
        s.add_instance("u_a", "mod_a").unwrap();
        s.add_instance("u_b", "mod_b").unwrap();
        s.set_port_map_entry(
            "u_b",
            "din",
            Some(NetRef::InstancePort("u_a".into(), "dout".into())),
        )
        .unwrap();
        s.set_alias(
            NetRef::InstancePort("u_a".into(), "dout".into()),
            "data_bus",
        );

        let lib = vec![
            ModuleDef {
                name: "mod_a".into(),
                generics: vec![],
                ports: vec![PortDef {
                    name: "dout".into(),
                    direction: Direction::Out,
                    port_type: PortType::StdLogic,
                    bundle: None,
                }],
                source_path: "a.vhd".into(),
                source_hash: 0,
                dependencies: Vec::new(),
            },
            ModuleDef {
                name: "mod_b".into(),
                generics: vec![],
                ports: vec![PortDef {
                    name: "din".into(),
                    direction: Direction::In,
                    port_type: PortType::StdLogic,
                    bundle: None,
                }],
                source_path: "b.vhd".into(),
                source_hash: 0,
                dependencies: Vec::new(),
            },
        ];

        let diags = s.validate(&lib);
        let output = generate_vhdl(&s, &lib, &diags).unwrap();

        assert!(output.contains("signal data_bus : std_logic;"));
        assert!(output.contains("din => data_bus"));
    }

    #[test]
    fn bilateral_slice_codegen_vhdl() {
        // inst_a.dout[7:4] => sig => inst_b.din[3:0]
        let mut s = Schematic::new("top", Language::Vhdl);
        s.add_instance("u_a", "mod_a").unwrap();
        s.add_instance("u_b", "mod_b").unwrap();
        // Driver-side slice on RHS (from u_a.dout[7:4]).
        s.set_port_map_entry(
            "u_b",
            "din",
            Some(NetRef::InstancePortSlice(
                "u_a".into(),
                "dout".into(),
                SliceExpr::Range { high: 7, low: 4 },
            )),
        )
        .unwrap();
        // Consumer-side slice on LHS (this port's [3:0] receives the driver slice).
        s.instances
            .iter_mut()
            .find(|i| i.name == "u_b")
            .unwrap()
            .consumer_slices
            .insert("din".into(), SliceExpr::Range { high: 3, low: 0 });

        let lib = vec![
            ModuleDef {
                name: "mod_a".into(),
                generics: vec![],
                ports: vec![PortDef {
                    name: "dout".into(),
                    direction: Direction::Out,
                    port_type: PortType::StdLogicVector(Range {
                        high: RangeExpr::Literal(7),
                        low: RangeExpr::Literal(0),
                        dir: RangeDir::Downto,
                    }),
                    bundle: None,
                }],
                source_path: "a.vhd".into(),
                source_hash: 0,
                dependencies: Vec::new(),
            },
            ModuleDef {
                name: "mod_b".into(),
                generics: vec![],
                ports: vec![PortDef {
                    name: "din".into(),
                    direction: Direction::In,
                    port_type: PortType::StdLogicVector(Range {
                        high: RangeExpr::Literal(7),
                        low: RangeExpr::Literal(0),
                        dir: RangeDir::Downto,
                    }),
                    bundle: None,
                }],
                source_path: "b.vhd".into(),
                source_hash: 0,
                dependencies: Vec::new(),
            },
        ];

        let diags = s.validate(&lib);
        let output = generate_vhdl(&s, &lib, &diags).unwrap();
        // LHS = din(3 downto 0), RHS = u_a_dout(7 downto 4)
        assert!(
            output.contains("din(3 downto 0) => u_a_dout(7 downto 4)"),
            "missing bilateral slice in VHDL output:\n{output}"
        );
    }

    #[test]
    fn alphabetical_instance_order() {
        let mut s = Schematic::new("top", Language::Vhdl);
        s.add_instance("u_z", "mod").unwrap();
        s.add_instance("u_a", "mod").unwrap();
        s.add_instance("u_m", "mod").unwrap();

        let lib = vec![ModuleDef {
            name: "mod".into(),
            generics: vec![],
            ports: vec![],
            source_path: "m.vhd".into(),
            source_hash: 0,
            dependencies: Vec::new(),
        }];

        let diags = s.validate(&lib);
        let output = generate_vhdl(&s, &lib, &diags).unwrap();

        let a_pos = output.find("u_a : mod").unwrap();
        let m_pos = output.find("u_m : mod").unwrap();
        let z_pos = output.find("u_z : mod").unwrap();
        assert!(a_pos < m_pos);
        assert!(m_pos < z_pos);
    }

    #[test]
    fn refuses_on_error() {
        let mut s = Schematic::new("top", Language::Vhdl);
        s.add_instance("u_fifo", "nonexistent").unwrap();

        let diags = s.validate(&[]);
        let result = generate_vhdl(&s, &[], &diags);
        assert!(result.is_err());
    }

    #[test]
    fn open_for_unconnected() {
        let mut s = Schematic::new("top", Language::Vhdl);
        s.add_instance("u_a", "mod_a").unwrap();

        let lib = vec![ModuleDef {
            name: "mod_a".into(),
            generics: vec![],
            ports: vec![PortDef {
                name: "unused".into(),
                direction: Direction::Out,
                port_type: PortType::StdLogic,
                bundle: None,
            }],
            source_path: "a.vhd".into(),
            source_hash: 0,
            dependencies: Vec::new(),
        }];

        // Warnings only (unconnected), not errors
        let diags: Vec<crate::schematic::Diagnostic> = s
            .validate(&lib)
            .into_iter()
            .filter(|d| d.is_error())
            .collect();

        let output = generate_vhdl(&s, &lib, &diags).unwrap();
        assert!(output.contains("unused => open"));
    }

    #[test]
    fn slice_variants_render_vhdl() {
        let mut s = Schematic::new("top", Language::Vhdl);
        s.add_instance("u_a", "mod_a").unwrap();
        s.add_instance("u_b", "mod_b").unwrap();
        // u_b.din1 = u_a.bus(0)      — single bit
        // u_b.din2 = u_a.bus(7 downto 4) — range
        s.set_port_map_entry(
            "u_b",
            "din1",
            Some(NetRef::InstancePortSlice(
                "u_a".into(),
                "bus".into(),
                SliceExpr::Bit(0),
            )),
        )
        .unwrap();
        s.set_port_map_entry(
            "u_b",
            "din2",
            Some(NetRef::InstancePortSlice(
                "u_a".into(),
                "bus".into(),
                SliceExpr::Range { high: 7, low: 4 },
            )),
        )
        .unwrap();

        let bus_type = PortType::StdLogicVector(Range {
            high: RangeExpr::Literal(7),
            low: RangeExpr::Literal(0),
            dir: RangeDir::Downto,
        });
        let din1_type = PortType::StdLogic;
        let din2_type = PortType::StdLogicVector(Range {
            high: RangeExpr::Literal(3),
            low: RangeExpr::Literal(0),
            dir: RangeDir::Downto,
        });
        let lib = vec![
            ModuleDef {
                name: "mod_a".into(),
                generics: vec![],
                ports: vec![PortDef {
                    name: "bus".into(),
                    direction: Direction::Out,
                    port_type: bus_type,
                    bundle: None,
                }],
                source_path: "a.vhd".into(),
                source_hash: 0,
                dependencies: Vec::new(),
            },
            ModuleDef {
                name: "mod_b".into(),
                generics: vec![],
                ports: vec![
                    PortDef {
                        name: "din1".into(),
                        direction: Direction::In,
                        port_type: din1_type,
                        bundle: None,
                    },
                    PortDef {
                        name: "din2".into(),
                        direction: Direction::In,
                        port_type: din2_type,
                        bundle: None,
                    },
                ],
                source_path: "b.vhd".into(),
                source_hash: 0,
                dependencies: Vec::new(),
            },
        ];

        let diags: Vec<crate::schematic::Diagnostic> = s
            .validate(&lib)
            .into_iter()
            .filter(|d| d.is_error())
            .collect();
        let output = generate_vhdl(&s, &lib, &diags).unwrap();
        assert!(output.contains("din1 => u_a_bus(0)"), "{output}");
        assert!(output.contains("din2 => u_a_bus(7 downto 4)"), "{output}");
    }

    fn generic_width_schematic(width_override: Option<&str>) -> (Schematic, Vec<ModuleDef>) {
        let mut s = Schematic::new("top", Language::Vhdl);
        // Top entity port whose type carries the child's WIDTH-1 expression.
        let derived_range = PortType::StdLogicVector(Range {
            high: RangeExpr::Expr("WIDTH-1".into()),
            low: RangeExpr::Literal(0),
            dir: RangeDir::Downto,
        });
        s.top_ports.push(PortDef {
            name: "dout".into(),
            direction: Direction::Out,
            port_type: derived_range.clone(),
            bundle: None,
        });
        s.top_ports.push(PortDef {
            name: "internal_load".into(),
            direction: Direction::In,
            port_type: derived_range.clone(),
            bundle: None,
        });
        s.add_instance("u_drv", "drv").unwrap();
        s.add_instance("u_load", "drv").unwrap();
        if let Some(w) = width_override {
            s.set_generic_map_entry("u_drv", "WIDTH", w).unwrap();
            s.set_generic_map_entry("u_load", "WIDTH", w).unwrap();
        }
        s.set_port_map_entry("u_drv", "bus", Some(NetRef::TopPort("dout".into())))
            .unwrap();
        // Wire u_load.in_bus to u_drv.bus to force an internal-net signal.
        s.set_port_map_entry(
            "u_load",
            "in_bus",
            Some(NetRef::InstancePort("u_drv".into(), "bus".into())),
        )
        .unwrap();

        let lib = vec![ModuleDef {
            name: "drv".into(),
            generics: vec![GenericDef {
                name: "WIDTH".into(),
                type_name: "integer".into(),
                default_value: Some("8".into()),
            }],
            ports: vec![
                PortDef {
                    name: "bus".into(),
                    direction: Direction::Out,
                    port_type: derived_range.clone(),
                    bundle: None,
                },
                PortDef {
                    name: "in_bus".into(),
                    direction: Direction::In,
                    port_type: derived_range,
                    bundle: None,
                },
            ],
            source_path: "drv.vhd".into(),
            source_hash: 0,
            dependencies: Vec::new(),
        }];

        (s, lib)
    }

    #[test]
    fn top_port_resolves_generic_default() {
        let (s, lib) = generic_width_schematic(None);
        let diags: Vec<_> = s
            .validate(&lib)
            .into_iter()
            .filter(|d| d.is_error())
            .collect();
        let output = generate_vhdl(&s, &lib, &diags).unwrap();
        assert!(
            output.contains("dout : out std_logic_vector(7 downto 0)"),
            "{output}"
        );
    }

    #[test]
    fn top_port_resolves_generic_override() {
        let (s, lib) = generic_width_schematic(Some("16"));
        let diags: Vec<_> = s
            .validate(&lib)
            .into_iter()
            .filter(|d| d.is_error())
            .collect();
        let output = generate_vhdl(&s, &lib, &diags).unwrap();
        assert!(
            output.contains("dout : out std_logic_vector(15 downto 0)"),
            "{output}"
        );
    }

    #[test]
    fn internal_net_resolves_generic_override() {
        let (s, lib) = generic_width_schematic(Some("16"));
        let diags: Vec<_> = s
            .validate(&lib)
            .into_iter()
            .filter(|d| d.is_error())
            .collect();
        let output = generate_vhdl(&s, &lib, &diags).unwrap();
        assert!(
            output.contains("signal u_drv_bus : std_logic_vector(15 downto 0);"),
            "{output}"
        );
    }
}
