-- Generated by hdl-compose. Edit the source .hdlc project file, not this file.

library ieee;
use ieee.std_logic_1164.all;

entity fixture_project is
  port (
    clk : in std_logic;
    dout : out std_logic_vector(7 downto 0);
    rst_n : in std_logic;
    full : out std_logic;
    empty : out std_logic
  );
end entity fixture_project;

architecture structural of fixture_project is

  signal clk_s : std_logic;
  signal dout_s : std_logic_vector(7 downto 0);
  signal rst_n_s : std_logic;
  signal full_s : std_logic;
  signal empty_s : std_logic;

  signal counter_0_count : std_logic_vector(7 downto 0);
  signal counter_0_msb : std_logic;

  component counter is
    generic (
      WIDTH : integer := 8
    );
    port (
      clk : in std_logic;
      rst_n : in std_logic;
      en : in std_logic;
      count : out std_logic_vector(WIDTH - 1 downto 0);
      msb : out std_logic
    );
  end component counter;

  component fifo_sync is
    generic (
      DEPTH : integer := 256;
      WIDTH : integer := 8
    );
    port (
      clk : in std_logic;
      rst_n : in std_logic;
      din : in std_logic_vector(WIDTH - 1 downto 0);
      wr_en : in std_logic;
      rd_en : in std_logic;
      dout : out std_logic_vector(WIDTH - 1 downto 0);
      full : out std_logic;
      empty : out std_logic
    );
  end component fifo_sync;

begin

  clk_s <= clk;
  dout <= dout_s;
  rst_n_s <= rst_n;
  full <= full_s;
  empty <= empty_s;

  counter_0 : counter
    port map (
      clk => clk_s,
      rst_n => rst_n_s,
      en => open,
      count => open,
      msb => open
    );

  fifo_sync_0 : fifo_sync
    port map (
      clk => clk_s,
      rst_n => rst_n_s,
      din => counter_0_count,
      wr_en => counter_0_msb,
      rd_en => open,
      dout => dout_s,
      full => full_s,
      empty => empty_s
    );

end architecture structural;
