#!/usr/bin/env python3
"""Build .hdlc project files for the synth (voice_chain + synth_top).

hdl-compose net convention (discovered empirically):
  - a port_map value names the NET by "<instance>_<port>" of the reference
  - therefore every OUTPUT that feeds other instances must reference ITSELF
    (creating the "<self>_<port>" net it drives), and every INPUT references
    the DRIVER's instance/port (joining that same net)
  - outputs going off-chip map to {"TopPort": ...}; unused outputs are null
  - inputs must never be null (codegen emits `open`, illegal VHDL for inputs)
"""
import json, sys

def slv(high, low=0):
    return {"StdLogicVector": {"high": {"Literal": high}, "low": {"Literal": low}, "dir": "Downto"}}

def port(name, direction, ptype):
    return {"name": name, "direction": direction, "port_type": ptype, "bundle": None}

def ip(inst_name, p):
    return {"InstancePort": [inst_name, p]}

def ips(inst_name, p, bit):
    return {"InstancePortSlice": [inst_name, p, {"Bit": bit}]}

def tp(name):
    return {"TopPort": name}

def inst(name, ref, generics=None, ports=None, pos=(0.0, 0.0)):
    return {"name": name, "module_ref": ref, "generic_map": generics or {},
            "port_map": ports or {}, "position": list(pos), "manual_bundles": {}}

LIB = [
    "rtl/registers/mapped_reg.vhd",
    "rtl/audio/bitwise_vec_op.vhd",
    "rtl/oscillator/phase_incre.vhd",
    "rtl/oscillator/square_wave.vhd",
    "rtl/oscillator/sawtooth.vhd",
    "rtl/oscillator/mux.vhd",
    "rtl/oscillator/volume_scaler.vhd",
    "rtl/audio/moving_average.vhd",
    "rtl/audio/output_stage.vhd",
    "rtl/cv/enveloper.vhd",
]

# ---------------------------------------------------------------- voice_chain

voice_chain = {
    "version": 4,
    "top_name": "voice_chain",
    "language": "Vhdl",
    "top_generics": [],
    "top_ports": [
        port("clk", "In", "StdLogic"),
        port("rstn", "In", "StdLogic"),
        port("note_state", "In", "StdLogic"),
        port("trigger", "In", "StdLogic"),
        port("note_index", "In", slv(6)),
        port("velocity", "In", slv(6)),
        port("param_write", "In", "StdLogic"),
        port("param_number", "In", slv(6)),
        port("param_value", "In", slv(6)),
        port("m_axis_out_tdata", "Out", slv(23)),
        port("m_axis_out_tvalid", "Out", "StdLogic"),
        port("m_axis_out_tready", "In", "StdLogic"),
        port("env_cv", "Out", slv(11)),
        port("env_gate", "Out", "StdLogic"),
    ],
    "instances": [
        inst("wave_reg", "mapped_reg",
             {"n": "7", "addr_size": "7", "address": "84", "output_width": "2"},
             {"D": tp("param_value"), "ADDR": tp("param_number"), "LOAD": tp("param_write"),
              "CLK": tp("clk"), "RSTN": tp("rstn"),
              "Q": ip("wave_reg", "Q")},
             (0, 0)),
        inst("dir_or", "bitwise_vec_op",
             {"OP": "\"OR\"", "SIZE": "2"},
             {"input_vector": ip("wave_reg", "Q"),
              "result": ip("dir_or", "result")},
             (200, 0)),
        inst("phase_incre_0", "phase_incre", {},
             {"clk": tp("clk"), "resetn": tp("rstn"),
              "phase_pkg": tp("note_index"), "update_freq": tp("trigger"),
              "m_axis_phase_tdata": ip("phase_incre_0", "m_axis_phase_tdata"),
              "m_axis_phase_tvalid": ip("phase_incre_0", "m_axis_phase_tvalid"),
              "m_axis_phase_tready": ip("square_0", "s_axis_square_tready")},
             (0, 200)),
        inst("square_0", "square", {},
             {"clk": tp("clk"), "resetn": tp("rstn"),
              "s_axis_square_tdata": ip("phase_incre_0", "m_axis_phase_tdata"),
              "s_axis_square_tvalid": ip("phase_incre_0", "m_axis_phase_tvalid"),
              "s_axis_square_tready": ip("square_0", "s_axis_square_tready"),
              "m_axis_square_tdata": ip("square_0", "m_axis_square_tdata"),
              "m_axis_square_tvalid": ip("square_0", "m_axis_square_tvalid"),
              "m_axis_square_tready": ip("mux_0", "s_axis_square_tready")},
             (200, 200)),
        inst("saw_0", "sawtooth_i", {"sample_depth": "24"},
             {"clk": tp("clk"), "resetn": tp("rstn"),
              "phase_idx": tp("note_index"), "phase_ready": tp("trigger"),
              "direction": ip("dir_or", "result"),
              "m_axis_saw_tdata": ip("saw_0", "m_axis_saw_tdata"),
              "m_axis_saw_tvalid": ip("saw_0", "m_axis_saw_tvalid"),
              "m_axis_saw_tready": ip("mux_0", "s_axis_saw_tready")},
             (200, 400)),
        inst("mux_0", "mux", {},
             {"clk": tp("clk"), "resetn": tp("rstn"),
              "sel": ip("wave_reg", "Q"),
              "s_axis_saw_tdata": ip("saw_0", "m_axis_saw_tdata"),
              "s_axis_saw_tvalid": ip("saw_0", "m_axis_saw_tvalid"),
              "s_axis_saw_tready": ip("mux_0", "s_axis_saw_tready"),
              "s_axis_square_tdata": ip("square_0", "m_axis_square_tdata"),
              "s_axis_square_tvalid": ip("square_0", "m_axis_square_tvalid"),
              "s_axis_square_tready": ip("mux_0", "s_axis_square_tready"),
              "s_axis_sine_tdata": ip("square_0", "m_axis_square_tdata"),
              "s_axis_sine_tvalid": ip("square_0", "m_axis_square_tvalid"),
              "s_axis_sine_tready": None,
              "m_axis_out_tdata": ip("mux_0", "m_axis_out_tdata"),
              "m_axis_out_tvalid": ip("mux_0", "m_axis_out_tvalid"),
              "m_axis_out_tready": ip("mov_avg", "s_axis_tready")},
             (400, 200)),
        inst("vol_scaler", "volume_scaler", {},
             {"clk": tp("clk"), "rstn": tp("rstn"),
              "en": tp("note_state"), "velocity": tp("velocity"),
              "s_axis_sample_tdata": ip("mux_0", "m_axis_out_tdata"),
              "s_axis_sample_tvalid": ip("mux_0", "m_axis_out_tvalid"),
              "m_axis_data_tdata": ip("vol_scaler", "m_axis_data_tdata"),
              "m_axis_data_tvalid": ip("vol_scaler", "m_axis_data_tvalid")},
             (600, 200)),
        inst("mov_avg", "moving_average", {},
             {"aclk": tp("clk"), "aresetn": tp("rstn"),
              "s_axis_tdata": ip("vol_scaler", "m_axis_data_tdata"),
              "s_axis_tvalid": ip("vol_scaler", "m_axis_data_tvalid"),
              "s_axis_tready": ip("mov_avg", "s_axis_tready"),
              "m_axis_tdata": ip("mov_avg", "m_axis_tdata"),
              "m_axis_tvalid": ip("mov_avg", "m_axis_tvalid"),
              "m_axis_tready": ip("out_stage", "s_axis_audio_tready")},
             (800, 200)),
        inst("out_stage", "output_stage", {},
             {"clk": tp("clk"), "enable": tp("note_state"),
              "s_axis_audio_tdata": ip("mov_avg", "m_axis_tdata"),
              "s_axis_audio_tvalid": ip("mov_avg", "m_axis_tvalid"),
              "s_axis_audio_tready": ip("out_stage", "s_axis_audio_tready"),
              "m_axis_out_tdata": tp("m_axis_out_tdata"),
              "m_axis_out_tvalid": tp("m_axis_out_tvalid"),
              "m_axis_out_tready": tp("m_axis_out_tready")},
             (1000, 200)),
        inst("env_0", "enveloper",
             {"ATTACK_ADDR": "73", "DECAY_ADDR": "75", "SUSTAIN_ADDR": "70",
              "RELEASE_ADDR": "72", "CLKS_PER_TICK": "104167"},
             {"clk": tp("clk"), "rst_n": tp("rstn"),
              "gate": tp("note_state"), "trig": tp("trigger"),
              "param_write": tp("param_write"), "param_addr": tp("param_number"),
              "param_data": tp("param_value"),
              "gate_out": tp("env_gate"), "env_out": tp("env_cv")},
             (600, 500)),
    ],
    "aliases": {},
    "library_paths": LIB,
}

# ------------------------------------------------------------------ synth_top

def voice(n):
    return inst(f"voice{n}", "voice_chain", {},
        {"clk": tp("clk"), "rstn": tp("rstn"),
         "note_state": ips("proc", "note_states", n),
         "trigger": ips("proc", "triggers", n),
         "note_index": ip("proc", "note_index"),
         "velocity": ip("proc", "velocity"),
         "param_write": ip("proc", "param_write"),
         "param_number": ip("proc", "param_number"),
         "param_value": ip("proc", "param_value"),
         "m_axis_out_tdata": ip(f"voice{n}", "m_axis_out_tdata"),
         "m_axis_out_tvalid": ip(f"voice{n}", "m_axis_out_tvalid"),
         "m_axis_out_tready": ip(f"cdc{n}", "s_tready"),
         "env_cv": ip(f"voice{n}", "env_cv"),
         "env_gate": tp(f"env_gate{n}")},
        (600, 100 + 400 * n))

def audio_path(n):
    """clk->mclk gray-code FIFO, I2S serializer, and pin buffers for one voice
    (pure-VHDL replacement for the BD i2s/outputs hierarchies)."""
    return [
        inst(f"cdc{n}", "axis_cdc", {"WIDTH": "24"},
             {"src_clk": tp("clk"), "src_rstn": tp("rstn"),
              "s_tdata": ip(f"voice{n}", "m_axis_out_tdata"),
              "s_tvalid": ip(f"voice{n}", "m_axis_out_tvalid"),
              "s_tready": ip(f"cdc{n}", "s_tready"),
              "dst_clk": tp("mclk"), "dst_rstn": tp("rstn"),
              "m_tdata": ip(f"cdc{n}", "m_tdata"),
              "m_tvalid": ip(f"cdc{n}", "m_tvalid"),
              "m_tready": ip(f"i2s{n}", "s_axis_in_tready")},
             (1400, 100 + 400 * n)),
        inst(f"i2s{n}", "i2s_transmitter", {"DATA_WIDTH": "24"},
             {"s_axis_in_clk": tp("mclk"), "resetn": tp("rstn"),
              "s_axis_in_tdata": ip(f"cdc{n}", "m_tdata"),
              "s_axis_in_tvalid": ip(f"cdc{n}", "m_tvalid"),
              "s_axis_in_tready": ip(f"i2s{n}", "s_axis_in_tready"),
              "bclk": ip(f"i2s{n}", "bclk"),
              "sdata": ip(f"i2s{n}", "sdata"),
              "lrclk": ip(f"i2s{n}", "lrclk")},
             (1600, 100 + 400 * n)),
        inst(f"selectio{n}", "selectio", {},
             {"clk_in": ip(f"i2s{n}", "bclk"),
              "data_out_from_device": ip(f"i2s{n}", "sdata"),
              "data_out_to_pins": tp(f"sdata{n}"),
              "clk_to_pins": tp(f"bclk_out{n}"),
              "clk_reset": tp("io_reset"), "io_reset": tp("io_reset")},
             (1800, 100 + 400 * n)),
        inst(f"obuf_lrclk{n}", "clock_obuf", {},
             {"clk_in": ip(f"i2s{n}", "lrclk"),
              "clk_to_pins": tp(f"lrclk_out{n}"),
              "clk_reset": tp("io_reset")},
             (1800, 200 + 400 * n)),
        inst(f"obuf_mclk{n}", "clock_obuf", {},
             {"clk_in": tp("mclk"),
              "clk_to_pins": tp(f"mclk_out{n}"),
              "clk_reset": tp("io_reset")},
             (1800, 300 + 400 * n)),
    ]

top = {
    "version": 4,
    "top_name": "synth_top",
    "language": "Vhdl",
    "top_generics": [],
    "top_ports": [
        port("clk", "In", "StdLogic"),
        port("rstn", "In", "StdLogic"),
        port("midi_clk", "In", "StdLogic"),
        port("midi_data", "In", "StdLogic"),
        port("midi_startn", "In", "StdLogic"),
        port("mclk", "In", "StdLogic"),
        port("io_reset", "In", "StdLogic"),
        port("sdata0", "Out", "StdLogic"),
        port("bclk_out0", "Out", "StdLogic"),
        port("lrclk_out0", "Out", "StdLogic"),
        port("mclk_out0", "Out", "StdLogic"),
        port("sdata1", "Out", "StdLogic"),
        port("bclk_out1", "Out", "StdLogic"),
        port("lrclk_out1", "Out", "StdLogic"),
        port("mclk_out1", "Out", "StdLogic"),
        port("env_gate0", "Out", "StdLogic"),
        port("env_gate1", "Out", "StdLogic"),
        port("DAC_SCLK", "Out", "StdLogic"),
        port("DAC_MOSI", "InOut", "StdLogic"),
        port("DAC_SS", "Out", "StdLogic"),
    ],
    "instances": [
        inst("midi_if", "midi_interface", {},
             {"sys_clk": tp("clk"), "sys_rstn": tp("rstn"),
              "midi_clk": tp("midi_clk"), "midi_sdata": tp("midi_data"),
              "midi_startn": tp("midi_startn"),
              "cpu_ack": ip("ed_update", "sig_out"),
              "midi_output": ip("midi_if", "midi_output"),
              "interrupt": None,
              "update": ip("midi_if", "update")},
             (0, 0)),
        inst("ed_update", "edge_detector", {},
             {"clk": tp("clk"), "rstn": tp("rstn"),
              "sig_in": ip("midi_if", "update"),
              "sig_out": ip("ed_update", "sig_out")},
             (150, 0)),
        # gray-code FIFO reused as the MIDI message queue (both ports on clk).
        # Popped by proc.ack (not read_midi): FWFT output must stay stable
        # until the processor has captured data_in.
        inst("midi_fifo", "axis_cdc", {"WIDTH": "16"},
             {"src_clk": tp("clk"), "src_rstn": tp("rstn"),
              "s_tdata": ip("midi_if", "midi_output"),
              "s_tvalid": ip("ed_update", "sig_out"),
              "s_tready": None,
              "dst_clk": tp("clk"), "dst_rstn": tp("rstn"),
              "m_tdata": ip("midi_fifo", "m_tdata"),
              "m_tvalid": ip("midi_fifo", "m_tvalid"),
              "m_tready": ip("proc", "read_midi")},
             (300, 0)),
        inst("proc", "midi_processor", {"VOICES": "2"},
             {"clk": tp("clk"), "rstn": tp("rstn"),
              "update": ip("midi_fifo", "m_tvalid"),
              "data_in": ip("midi_fifo", "m_tdata"),
              "read_midi": ip("proc", "read_midi"),
              "ack": None,
              "triggers": ip("proc", "triggers"),
              "note_stops": None,
              "note_states": ip("proc", "note_states"),
              "note_index": ip("proc", "note_index"),
              "velocity": ip("proc", "velocity"),
              "param_write": ip("proc", "param_write"),
              "param_number": ip("proc", "param_number"),
              "param_value": ip("proc", "param_value")},
             (450, 0)),
        voice(0),
        voice(1),
        *audio_path(0),
        *audio_path(1),
        inst("vcf_gate_or", "bitwise_vec_op", {"OP": "\"OR\"", "SIZE": "2"},
             {"input_vector": ip("proc", "note_states"),
              "result": ip("vcf_gate_or", "result")},
             (600, 900)),
        inst("vcf_trig_or", "bitwise_vec_op", {"OP": "\"OR\"", "SIZE": "2"},
             {"input_vector": ip("proc", "triggers"),
              "result": ip("vcf_trig_or", "result")},
             (600, 1000)),
        inst("env_vcf", "enveloper",
             {"ATTACK_ADDR": "80", "DECAY_ADDR": "81", "SUSTAIN_ADDR": "82",
              "RELEASE_ADDR": "83", "CLKS_PER_TICK": "104167"},
             {"clk": tp("clk"), "rst_n": tp("rstn"),
              "gate": ip("vcf_gate_or", "result"),
              "trig": ip("vcf_trig_or", "result"),
              "param_write": ip("proc", "param_write"),
              "param_addr": ip("proc", "param_number"),
              "param_data": ip("proc", "param_value"),
              "gate_out": None,
              "env_out": ip("env_vcf", "env_out")},
             (800, 900)),
        inst("lfo_0", "lfo", {"RATE_ADDR": "85", "CLKS_PER_TICK": "10417"},
             {"clk": tp("clk"), "rst_n": tp("rstn"),
              "param_write": ip("proc", "param_write"),
              "param_addr": ip("proc", "param_number"),
              "param_data": ip("proc", "param_value"),
              "lfo_out": ip("lfo_0", "lfo_out")},
             (800, 1100)),
        inst("mix", "cv_mix", {"DEPTH_ADDR": "86"},
             {"clk": tp("clk"), "rst_n": tp("rstn"),
              "param_write": ip("proc", "param_write"),
              "param_addr": ip("proc", "param_number"),
              "param_data": ip("proc", "param_value"),
              "env_in": ip("env_vcf", "env_out"),
              "lfo_in": ip("lfo_0", "lfo_out"),
              "cv_out": ip("mix", "cv_out")},
             (1000, 1000)),
        inst("dac", "i2c_cv_dac", {"CLK_DIV": "260"},
             {"clk": tp("clk"), "rst_n": tp("rstn"),
              "ch_a": ip("voice0", "env_cv"),
              "ch_b": ip("voice1", "env_cv"),
              "ch_c": ip("mix", "cv_out"),
              "scl": tp("DAC_SCLK"),
              "sda": tp("DAC_MOSI"),
              "ldac": tp("DAC_SS")},
             (1200, 1000)),
    ],
    "aliases": {},
    "library_paths": LIB + [
        "rtl/midi/midi_interface.vhd",
        "rtl/midi/midi_processor.vhd",
        "rtl/midi/edge_detect.vhd",
        "rtl/cv/lfo.vhd",
        "rtl/cv/cv_mix.vhd",
        "rtl/cv/i2c_cv_dac.vhd",
        "rtl/gen/voice_chain.vhd",
        "rtl/cv/axis_cdc.vhd",
        "rtl/audio/i2s_manager.vhd",
        "rtl/audio/clocked_data_out.v",
        "rtl/audio/clock_obuf.vhd",
    ],
}

with open("voice_chain.hdlc", "w") as f:
    json.dump(voice_chain, f, indent=2)
print("wrote voice_chain.hdlc")
with open("synth_top.hdlc", "w") as f:
    json.dump(top, f, indent=2)
print("wrote synth_top.hdlc")
